LineLength:
  Max: 80
MethodLength:
  Max: 7
ClassLength:
  Max: 100
FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '**/config/**/*'
    - '**/bin/**/*'
    - '**/Rakefile'
    - '**/spec/**/*'
    - '**/db//**/*'
